import test from 'node:test';import assert from 'node:assert/strict';
import {metaPort} from '../skills/woia-ads-platforms/scripts/meta-port.mjs';
import {digest} from '../skills/woia-ads-platforms/scripts/authority-effect.mjs';
const c={action:'ads.campaign.pause',organization:'org',scope:'scope',resource_id:'c',effect_id:'e',expected_revision:0,payload:{meta:{account_id:'act_123',api_version:'v24.0',target_id:'456'}}};
function context(command=c){return{authenticated:true,organization:'org',scope:'scope',actor_id:'a',task_id:'t',department:'Ads',writer:'Ads',now:1,expires_at:10,source_current:true,conflict:false,actions:[command.action],policy_revision:'p',binding_revision:'b',authority_revision:'a',approval:{result:'APPROVED',approver:'human',command_digest:digest(command),policy_revision:'p',binding_revision:'b',authority_revision:'a',expires_at:10}}}
const binding={version:'v24.0',account_id:'act_123',token:'synthetic-token',binding_revision:'b',persist:async()=>{},context:context()};
test('Meta campaign creation routes to account without invented campaign target',async()=>{const create={...c,action:'ads.campaign.create',payload:{name:'campaign',meta:{account_id:'act_123',api_version:'v24.0',objective:'OUTCOME_LEADS',special_ad_categories:['HOUSING']}}};let request;const port=metaPort({...binding,context:context(create),qualification:'PASS',fetchImpl:async(url,options)=>{request={url,options};return{ok:true,json:async()=>({id:'999'})}}});const result=await port.execute(create);assert.equal(request.url,'https://graph.facebook.com/v24.0/act_123/campaigns');assert.equal(request.options.body.get('status'),'PAUSED');assert.equal(result.status,'SUCCEEDED')});
test('Meta fail closed without qualification',async()=>{let calls=0;const port=metaPort({...binding,qualification:'NOT_RUN',fetchImpl:async()=>{calls++}});await assert.rejects(port.execute(c),/QUALIFIED/);assert.equal(calls,0)});
test('Meta builds exact campaign route and prevents redirect',async()=>{let req;const port=metaPort({...binding,qualification:'PASS',fetchImpl:async(url,options)=>{req={url,options};return{ok:true,json:async()=>({success:true})}}});const result=await port.execute(c);assert.equal(req.url,'https://graph.facebook.com/v24.0/456');assert.equal(req.options.body.get('status'),'PAUSED');assert.equal(req.options.redirect,'error');assert.equal(result.status,'SUCCEEDED');assert.ok(!JSON.stringify(result).includes('synthetic-token'))});
test('Meta errors retain ambiguity',async()=>{const port=metaPort({...binding,qualification:'PASS',fetchImpl:async()=>({ok:false,status:503,json:async()=>({error:{code:2}})})});assert.equal((await port.execute(c)).status,'UNKNOWN')});
test('Meta binding mismatch blocks',async()=>{const changed=structuredClone(c);changed.payload.meta.account_id='act_999';const port=metaPort({...binding,context:context(changed),qualification:'PASS'});await assert.rejects(port.execute(changed),/EXACT_META/)});
