import test from 'node:test';import assert from 'node:assert/strict';
import {apply,initialState as createState,actions,projectSucceeded} from '../skills/woia-ads-platforms/scripts/provider.mjs';
const initialState=()=>createState('org','scope');
import {digest,beginEffect,dispatchPending,reconcileEffect} from '../skills/woia-ads-platforms/scripts/authority-effect.mjs';
function command(action='ads.campaign.create',payload={campaign_id:'camp',name:'synthetic',initial_status:'PAUSED'}){return{action,organization:'org',scope:'scope',resource_id:'camp',effect_id:'e1',expected_revision:0,payload}}
function auth(c){return{authenticated:true,organization:'org',scope:'scope',task_id:'t',actor_id:'actor',department:'Ads',writer:'Ads',now:10,expires_at:100,source_current:true,conflict:false,actions:[...actions],policy_revision:'p1',binding_revision:'b1',authority_revision:'a1',approval:{approver:'human',result:'APPROVED',command_digest:digest(c),policy_revision:'p1',binding_revision:'b1',authority_revision:'a1',expires_at:99}}}
test('all required actions exported',()=>assert.equal(actions.length,11));
test('update cannot activate or archive campaign or overwrite identity',()=>{const s=initialState();s.campaigns.camp={status:'PAUSED'};for(const extra of [{status:'ACTIVE'},{status:'ARCHIVED'},{campaign_id:'other'}]){const c=command('ads.campaign.update',{name:'new',...extra});assert.throws(()=>apply(s,c,auth(c)),/ACTION_PAYLOAD_FORBIDDEN/)} });
test('CAS rejection never invokes adapter',async()=>{const c=command(),a=auth(c),s=beginEffect(initialState(),c,a,'Ads').state;let calls=0;await assert.rejects(dispatchPending(s,c,a,'Ads',{qualification:'PASS',binding_revision:'b1',persist:async()=>false,execute:async()=>{calls++}}),/DURABLE_CAS/);assert.equal(calls,0)});
test('state isolation rejects another organization',()=>{const c=command(),s=initialState();s.organization='other';assert.throws(()=>apply(s,c,auth(c)),/STATE_SCOPE/)});
test('read still requires current explicit grant',()=>{const c=command('ads.performance.read',{});const a=auth(c);a.department='Other';assert.doesNotThrow(()=>apply(initialState(),c,a));a.actions=[];assert.throws(()=>apply(initialState(),c,a),/ACTION/)});
test('valid exact effect stages without input mutation',()=>{const c=command(),s=initialState(),r=apply(s,c,auth(c));assert.equal(r.effect.status,'PENDING');assert.equal(s.revision,0);assert.equal(r.state.revision,1)});
for(const [name,change] of [['wrong owner',a=>a.department='Other'],['revoked',a=>a.revoked=true],['hold',a=>a.hold=true],['stale source',a=>a.source_current=false],['conflict',a=>a.conflict=true],['wrong scope',a=>a.scope='other'],['self approval',a=>a.approval.approver='actor'],['changed binding',a=>a.binding_revision='b2'],['expiry',a=>a.now=200],['unauthenticated',a=>a.authenticated=false],['no action grant',a=>a.actions=[]]]){
test('reject '+name,()=>{const c=command(),a=auth(c);change(a);assert.throws(()=>apply(initialState(),c,a))})}
test('payload change invalidates approval',()=>{const c=command(),a=auth(c);c.payload.extra='changed';assert.throws(()=>apply(initialState(),c,a),/EXACT_APPROVAL/)});
test('stale expected revision blocks',()=>{const c=command();c.expected_revision=9;assert.throws(()=>apply(initialState(),c,auth(c)),/REVISION/)});
test('same identity never blindly dispatches again',()=>{const c=command(),a=auth(c),r=beginEffect(initialState(),c,a,'Ads');r.state.revision=0;r.state.effects['org/scope/e1'].status='UNKNOWN';assert.equal(beginEffect(r.state,c,a,'Ads').dispatch,false)});
test('idempotency conflicts rejected',()=>{const c=command(),r=beginEffect(initialState(),c,auth(c),'Ads');r.state.revision=0;c.payload.changed=true;assert.throws(()=>beginEffect(r.state,c,auth(c),'Ads'),/IDEMPOTENCY/)});
test('unknown durably retained before network failure',async()=>{const c=command(),a=auth(c),s=beginEffect(initialState(),c,a,'Ads').state;let saved;const r=await dispatchPending(s,c,a,'Ads',{qualification:'PASS',binding_revision:'b1',persist:async n=>{saved=n;return true},execute:async()=>{assert.equal(saved.effects['org/scope/e1'].status,'UNKNOWN');throw Error('network')}});assert.equal(r.effects['org/scope/e1'].status,'UNKNOWN');await assert.rejects(dispatchPending(r,c,a,'Ads',{}),/PENDING/)});
test('unqualified port fails before contact',async()=>{const c=command(),a=auth(c),s=beginEffect(initialState(),c,a,'Ads').state;await assert.rejects(dispatchPending(s,c,a,'Ads',{qualification:'NOT_RUN'}),/QUALIFIED/)});
test('reconciliation requires attributable matching evidence',()=>{const c=command(),s=beginEffect(initialState(),c,auth(c),'Ads').state;const rc={...c,action:'ads.effect.reconcile',expected_revision:1,payload:{effect_id:'e1',status:'SUCCEEDED',source_id:'source',evidence_id:'evidence'}};assert.equal(reconcileEffect(s,rc,auth(rc),'Ads').effects['org/scope/e1'].status,'SUCCEEDED');delete rc.payload.evidence_id;assert.throws(()=>reconcileEffect(s,rc,auth(rc),'Ads'),/ATTRIBUTED/)});
test('campaign initial state must be paused',()=>{const c=command();c.payload.initial_status='ACTIVE';assert.throws(()=>apply(initialState(),c,auth(c)),/PAUSED/)});
test('budget requires exact integer currency units',()=>{const s=initialState();s.campaigns.camp={status:'PAUSED'};const c=command('ads.budget.set',{amount_minor:'0.10',currency:'USD',scale:2,budget_period:'daily'});assert.throws(()=>apply(s,c,auth(c)),/SPEND/);c.payload.amount_minor='10';assert.equal(apply(s,c,auth(c)).dispatch,true)});
test('person messaging forbidden',()=>{const c=command();c.payload.message='hello';assert.throws(()=>apply(initialState(),c,auth(c)),/PERSON/)});
test('human inquiry routes through Communications/Customer Service',()=>{const c=command('ads.signal.observe',{kind:'lead',source_id:'meta:source',evidence_id:'ev',observed_at:1,external_ref:'lead',attribution:{campaign_id:'camp'}});const r=apply(initialState(),c,auth(c));assert.deepEqual(r.interaction.route,['woia-communications','Customer Service']);assert.equal(r.interaction.accepted,false);assert.equal(r.state.signals[0].attribution.campaign_id,'camp')});
test('archived campaign cannot resume',()=>{const s=initialState();s.campaigns.camp={status:'ARCHIVED'};const c=command('ads.campaign.resume',{});assert.throws(()=>apply(s,c,auth(c)),/ACTIVE_CAMPAIGN/)})
